name: Create Release for new Tag

on:
  push:
    tags:        
      - '**'

jobs:

  build:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./IsaacOnlineModded/IsaacOnlineModded.csproj

      - name: Publish project
        run: dotnet publish ./IsaacOnlineModded/IsaacOnlineModded.csproj /p:PublishProfile=FolderProfile
        
      - name: Publish project self-contained
        run: dotnet publish ./IsaacOnlineModded/IsaacOnlineModded.csproj /p:PublishProfile=FolderProfile2
          
      - name: Compress Self-Contained Binaries
        run: |
          powershell Compress-Archive -Path ./IsaacOnlineModded/BinariesSelfContained/* -DestinationPath ./BinariesWithRuntime.zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "IsaacOnlineModded/Binaries/IsaacOnlineModded.exe,BinariesWithRuntime.zip"
          name: IsaacOnlineModded Patcher Release ${{ github.ref_name }}